# These are supported funding model platforms
open_collective: https://opencollective.com/nullables/
patreon: AlexRogalskiy
ko_fi: https://ko-fi.com/alexrogalskiy
issuehunt: https://issuehunt.io/r/AlexRogalskiy/
custom: [ "https://www.nullables.io/" ]
