github:
  description: "Object Mappers Playground"
  homepage: https://github.com/AlexRogalskiy/object-mappers-playground/
  labels:
    - java
    - object mappings
    - benchmarks
  features:
    # Enable wiki for documentation
    wiki: true
    # Enable issue management
    issues: true
    # Enable projects for project management boards
    projects: true
  enabled_merge_buttons:
    # enable squash button:
    squash: true
    # enable merge button:
    merge: true
    # disable rebase button:
    rebase: false
  ghp_branch: master
  ghp_path: /docs
  protected_branches:
    master:
      required_status_checks:
        strict: true
        contexts:
          - Build LicenseEye
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        required_approving_review_count: 1

notifications:
  commits: alexander.rogalsky@yandex.ru
  issues: alexander.rogalsky@yandex.ru
  pullrequests: alexander.rogalsky@yandex.ru
