# global default
container:
  image: maven:latest

task:
  name: Cirrus CI
  before_cache_script: rm -rf $HOME/.m2/repository
  maven_cache:
    folder: ~/.m2
  matrix:
    - name: Build
      only_if: $BRANCH == "master"
      fingerprint_script: mvn --version
      build_script: |
        mvn clean package --file pom.xml --show-version --batch-mode --errors --lax-checksums -DskipTests=true -P"test-jar","dev"
      container:
        image: openjdk:11-jdk
        cpu: 2
        memory: 4G
    - name: Test
      depends_on:
        - Build
      allow_failures: true
      only_if: $BRANCH == "master"
      fingerprint_script: mvn --version
      test_script: |
        mvn test verify --file pom.xml --show-version --batch-mode --errors --lax-checksums -P"test","test-jar","dev"
      container:
        image: openjdk:12-jdk
        cpu: 2
        memory: 4G
  #  build_script: mvn clean package --file pom.xml --show-version --batch-mode --errors --lax-checksums -DskipTests=true -P"test-jar","dev"
  #  test_script: mvn test verify --file pom.xml --show-version --batch-mode --errors --lax-checksums -P"test","test-jar","dev"
