codecov:
  notify:
    require_ci_to_pass: yes
  strict_yaml_branch: master
  branch: master

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        informational: true
        target: 95%
        threshold: 0.5
    patch:
      default:
        informational: true
        target: 80%
    changes: no

  notify:
    # Wait for reasonable amount of tests to complete before
    # reporting coverage
    after_n_builds: 8

  ignore:
    - "**/generated/**"
    - "standalone"
    - "test"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: reach, changes, diff, files
  behavior: default
  require_changes: false
