version: "2"

engines:
  sonar-java:
    enabled: true
    channel: beta
    checks:
      squid:S00112: # Requires dedicated exceptions even for tests
        enabled: false
    config:
      sonar.java.source: 1.8
      minimum_severity: critical
      tests_patterns:
        - src/test/**

checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false

plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-82
  pmd:
    enabled: true
    config:
      rules:
        - "java-basic"
        - "java-design"
        - "java-android"

ratings:
  paths:
    - "**.java"

exclude_paths:
  - build/
  - .mvn/
  - .github/
  - spec/**/*
  - vendor/**/*
  - test/**/*
  - generated/**/*
