codecov:
  notify:
    require_ci_to_pass: yes
  strict_yaml_branch: master
  branch: master

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: true
    patch: yes
    changes: no

  ignore:
    - "**/generated/**"
    - "standalone"
    - "test"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: false
