queries:
  # Start by hiding the results of all queries.
  - exclude: "*"
  # Then include all queries tagged 'security' and 'correctness', and with a severity of
  # 'error'.
  - include:
      tags:
        - "security"
        - "correctness"
      severity: "error"

extraction:
  java:
    after_prepare:
      - export PATH=$LGTM_WORKSPACE/tools:$PATH
        index:
    java_version: 11
    xml_mode: all
      maven:
  settings_file: /.mvn/settings.xml
    version: 3.6.3
    build_command:
      - ./mvnw clean package --file pom.xml --show-version --batch-mode --errors --lax-checksums -DskipTests=true -P"test-jar","dev"

path_classifiers:
  docs:
    - "LICENSE*"
    - "*.md"
    - "*.html"
  ci:
    - "appveyor.yml"
    - ".codecov.yml"
    - ".travis.yml"
    - ".circleci"
    - ".dependabot"
  generated:
    exclude: "**/*.java"
