language: java

dist: trusty

git:
  depth: false
  quiet: true
  submodules: false
  lfs_skip_smudge: true

sudo: false

install: true

branches:
  only:
    - master
    - develop
    - /^release.*$/

jdk:
  - oraclejdk8
  - openjdk8

before_script:
  - mvn -N io.takari:maven:wrapper -Dmaven=3.6.3

script:
  - |
    set -o pipefail
    if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ -n "${GITHUB_TOKEN:-}" ]; then
      ./mvnw clean install sonar:sonar --file pom.xml --errors --batch-mode --lax-checksums -DskipTests=true -P"non_module_java","test-jar","dev" \
        -Dsonar.projectKey=object-mappers-playground \
        -Dsonar.organization=alexrogalskiy-github \
        -Dsonar.analysis.mode=preview \
        -Dsonar.github.pullRequest=${TRAVIS_PULL_REQUEST} \
        -Dsonar.github.repository=${TRAVIS_REPO_SLUG} \
        -Dsonar.github.oauth=${GITHUB_TOKEN} \
        -Dsonar.login=${SONAR_TOKEN} \
        -Dsonar.host.url=https://sonarcloud.io/ \
        -Dsonar.coverage.jacoco.xmlReportPaths=./build/site/jacoco/jacoco.xml \
        2>&1 \
      | grep ^\\[
    else
      ./mvnw clean package install --file pom.xml --show-version --batch-mode --errors --lax-checksums -DskipTests=true -P"non_module_java","test-jar","dev" 2>&1 | grep ^\\[
    fi

notifications:
  email:
    on_success: change
    on_failure: always

cache:
  directories:
    - "$HOME/.m2/repository"
