site_name: ObjectMappers Documentation
site_description: Object mappers - how to eat it and how to make it
site_author: Alexander Rogalskiy

repo_name: "AlexRogalskiy/object-mappers-playground"
repo_url: https://gitlab.com/AlexRogalskiy/object-mappers-playground

theme:
  name: material
  palette:
    primary: red
    accent: red
  #logo: assets/logo.png
  feature:
    tabs: true

edit_uri: edit/develop/docs

markdown_extensions:
  - meta
  - footnotes
  - codehilite
  - admonition

pages:
  - Welcome: index.md
  - Information: info.md
  - User Guide:
      - Changelog: user-guide/changelog.md
      - Dependency: user-guide/dependency.md
      - FAQ: user-guide/faq.md
      - Getting Started: user-guide/getting-started.md
      - Description: user-guide/description.md
      - Code of Conduct: user-guide/code_of_conduct.md
      - Code Owners: user-guide/code_owners.md
      - Troubleshooting: user-guide/troubleshooting.md
      - Upgrade: user-guide/upgrade.md
  - Modules:
      - BeanCp: modules/beancp/readme.md
      - Bull: modules/bull/readme.md
      - Datus: modules/datus/readme.md
      - Dozer: modules/dozer/readme.md
      - JMapper: modules/jmapper/readme.md
      - MapStruct: modules/mapstruct/readme.md
      - ModelMapper: modules/modelmapper/readme.md
      - Moo: modules/moo/readme.md
      - Nomin: modules/nomin/readme.md
      - Orika: modules/orika/readme.md
      - ReMap: modules/remap/readme.md
      - Selma: modules/selma/readme.md
  - Contributing:
      - Information: contributing/info.md
  - Reporting:
      - Information: reporting/info.md
      - Bug Report: reporting/bug_report.md
      - Custom Report: reporting/custom_report.md
      - Feature Requst: reporting/feature_request_template.md
      - Pull Requst Template: reporting/pull_request_template.md
