site_name: ObjectMappers Documentation
site_description: >
  Object mappers playground
site_author: Alexander Rogalskiy
site_url: https://alexander-rogalsky.gitbook.io/object-mappers-docs/

repo_name: AlexRogalskiy/object-mappers-playground
repo_url: https://gitlab.com/AlexRogalskiy/object-mappers-playground
edit_uri: https://gitlab.com/AlexRogalskiy/object-mappers-playground/master/docs/

#Copyright (shown at the footer)
copyright: 'Copyright &copy; 2016-2020 Nullables.io'

theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    scheme: preference
    primary: deep-orange
    accent: deep-orange
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - header.autohide
  highlightjs: true
  language: 'en'

plugins:
  - search
#  - minify:
#      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/AlexRogalskiy/object-mappers-playground

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      use_pygments: false
  - markdown.extensions.def_list
  - markdown.extensions.attr_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true

pages:
  - Introduction: index.md
  - User Guide:
      - Changelog: user-guide/changelog.md
      - Dependency: user-guide/dependency.md
      - FAQ: user-guide/faq.md
      - Getting Started: user-guide/getting-started.md
      - Code of Conduct: user-guide/code_of_conduct.md
      - Code Owners: user-guide/code_owners.md
      - Troubleshooting: user-guide/troubleshooting.md
      - Upgrade: user-guide/upgrade.md
      - Cloning content: user-guide/how-to-move-content.md
  - Modules:
      - BeanCp Tutorial: modules/beancp/info.md
      - BeanMapper Tutorial: modules/beanmapper/info.md
      - BeanUtils Tutorial: modules/beanutils/info.md
      - Bull Tutorial: modules/bull/info.md
      - Converter Tutorial: modules/converter/info.md
      - Datus Tutorial: modules/datus/info.md
      - Doov Tutorial: modules/doov/info.md
      - Dozer Tutorial: modules/dozer/info.md
      - JMapper Tutorial: modules/jmapper/info.md
      - MapStruct Tutorial: modules/mapstruct/info.md
      - ModelMapper Tutorial: modules/modelmapper/info.md
      - Moo Tutorial: modules/moo/info.md
      - Nomin Tutorial: modules/nomin/info.md
      - Orika Tutorial: modules/orika/info.md
      - ReMap Tutorial: modules/remap/info.md
      - Selma Tutorial: modules/selma/info.md
      - Smooks Tutorial: modules/smooks/info.md
  - Issues: "https://github.com/AlexRogalskiy/object-mappers-playground/issues"
  - Contributing:
      - Information: contributing/info.md
  - Reporting:
      - Information: reporting/info.md
      - Bug Report: reporting/bug_report.md
      - Custom Report: reporting/custom_report.md
      - Issue Report: reporting/issue_template.md
      - Feature Requst: reporting/feature_request_template.md
      - Pull Requst: reporting/pull_request_template.md
  - Links:
      - Information: links/info.md
