site_name: ObjectMappers Documentation
site_description: Object mappers - how to eat it and how to make it
site_author: Alexander Rogalskiy

repo_name: "AlexRogalskiy/object-mappers-playground"
repo_url: https://gitlab.com/AlexRogalskiy/object-mappers-playground

theme:
  name: material
  palette:
    primary: red
    accent: red
  feature:
    tabs: true

edit_uri: edit/develop/docs

markdown_extensions:
  - meta
  - footnotes
  - codehilite
  - admonition

pages:
  - Welcome: index.md
  - User Guide:
      - Changelog: user-guide/changelog.md
      - Dependency: user-guide/dependency.md
      - FAQ: user-guide/faq.md
      - Getting Started: user-guide/getting-started.md
      - Code of Conduct: user-guide/code_of_conduct.md
      - Code Owners: user-guide/code_owners.md
      - Troubleshooting: user-guide/troubleshooting.md
      - Upgrade: user-guide/upgrade.md
  - Modules:
      - BeanCp: modules/beancp/info.md
      - BeanMapper: modules/beanmapper/info.md
      - BeanUtils: modules/beanutils/info.md
      - Bull: modules/bull/info.md
      - Converter: modules/converter/info.md
      - Datus: modules/datus/info.md
      - Dozer: modules/dozer/info.md
      - JMapper: modules/jmapper/info.md
      - MapStruct: modules/mapstruct/info.md
      - ModelMapper: modules/modelmapper/info.md
      - Moo: modules/moo/info.md
      - Nomin: modules/nomin/info.md
      - Orika: modules/orika/info.md
      - ReMap: modules/remap/info.md
      - Selma: modules/selma/info.md
      - Smooks: modules/smooks/info.md
  - Contributing:
      - Information: contributing/info.md
  - Reporting:
      - Information: reporting/info.md
      - Bug Report: reporting/bug_report.md
      - Custom Report: reporting/custom_report.md
      - Feature Requst: reporting/feature_request_template.md
      - Pull Requst Template: reporting/pull_request_template.md
  - Links:
      - Information: links/info.md
