site_name: ObjectMappers Documentation
repo_url: https://gitlab.com/AlexRogalskiy/object-mappers-playground
theme: material
pages:
  - Welcome: index.md
  - Information: info.md
  - User Guide:
      - Changelog: user-guide/changelog.md
      - Dependency: user-guide/dependency.md
      - FAQ: user-guide/faq.md
      - Getting Started: user-guide/getting-started.md
      - Description: user-guide/description.md
      - Code of Conduct: user-guide/code_of_conduct.md
      - Code Owners: user-guide/code_owners.md
      - Troubleshooting: user-guide/troubleshooting.md
      - Upgrade: user-guide/upgrade.md
  - Contributing:
      - Information: contributing/info.md
  - Reporting:
      - Information: reporting/info.md
      - Bug Report: reporting/bug_report.md
      - Custom Report: reporting/custom_report.md
      - Feature Requst: reporting/feature_request_template.md
      - Pull Requst Template: reporting/pull_request_template.md
