name: object-mappers
version: '1.0.0'
version-script: |
  echo $(cat VERSION)-$(date +%Y%m%d)+$(git rev-parse --short HEAD)
summary: |
  Object mappers playground
description: |
  Free and open source software application that considered different options for
  end-to-end object mappings

architectures:
  - build-on: armhf
  - build-on: arm64
  - build-on: amd64
  - build-on: i386

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
base: core18

parts:
  object-mappers:
    plugin: maven
    source: https://github.com/AlexRogalskiy/object-mappers-playground.git
    maven-openjdk-version: "11"
    maven-targets:
      - modules/objectmappers-all/.build/bin/io.nullables.api.playground.objectmappers.all/*.jar
      - modules/objectmappers-beancp/.build/bin/io.nullables.api.playground.objectmappers.beancp/*.jar
      - modules/objectmappers-beanmapper/.build/bin/io.nullables.api.playground.objectmappers.beanmapper/*.jar
      - modules/objectmappers-beanutils/.build/bin/io.nullables.api.playground.objectmappers.beanutils/*.jar
      - modules/objectmappers-benchmarks/.build/bin/io.nullables.api.playground.objectmappers.benchmarks/*.jar
      - modules/objectmappers-bull/.build/bin/io.nullables.api.playground.objectmappers.bull/*.jar
      - modules/objectmappers-commons/.build/bin/io.nullables.api.playground.objectmappers.commons/*.jar
      - modules/objectmappers-datus/.build/bin/io.nullables.api.playground.objectmappers.datus/*.jar
      - modules/objectmappers-doov/.build/bin/io.nullables.api.playground.objectmappers.doov/*.jar
      - modules/objectmappers-dozer/.build/bin/io.nullables.api.playground.objectmappers.dozer/*.jar
      - modules/objectmappers-it/.build/bin/io.nullables.api.playground.objectmappers.it/*.jar
      - modules/objectmappers-jmapper/.build/bin/io.nullables.api.playground.objectmappers.jmapper/*.jar
      - modules/objectmappers-mapstruct/.build/bin/io.nullables.api.playground.objectmappers.mapstruct/*.jar
      - modules/objectmappers-modelmapper/.build/bin/io.nullables.api.playground.objectmappers.modelmapper/*.jar
      - modules/objectmappers-moo/.build/bin/io.nullables.api.playground.objectmappers.moo/*.jar
      - modules/objectmappers-nomin/.build/bin/io.nullables.api.playground.objectmappers.nomin/*.jar
      - modules/objectmappers-orika/.build/bin/io.nullables.api.playground.objectmappers.orika/*.jar
      - modules/objectmappers-remap/.build/bin/io.nullables.api.playground.objectmappers.remap/*.jar
      - modules/objectmappers-selma/.build/bin/io.nullables.api.playground.objectmappers.selma/*.jar
      - modules/objectmappers-smooks/.build/bin/io.nullables.api.playground.objectmappers.smooks/*.jar
      - modules/objectmappers-testflow/.build/bin/io.nullables.api.playground.objectmappers.testflow/*.jar
    source-type: git
    source-branch: master
    source-depth: 1
    maven-options:
      - --batch-mode
      - --show-version
      - --errors
      - --lax-checksums
      - -DskipTests=true
      - -P test-jar, dev
    override-build: |
      mvn clean package --show-version --batch-mode --errors --lax-checksums -DskipTests=true -P"test-jar","dev"
    build-packages:
      - openjdk-11-jdk
      - unzip
      - maven
    stage-packages:
      - openjdk-11-jre

apps:
  object-mappers:
    extensions:
      - gnome-3-28
    command: java $JAVA_OPTS -jar ./modules/objectmappers-benchmarks/.build/bin/io.nullables.api.playground.objectmappers.benchmarks/benchmarks.jar
    environment:
      JAVA_OPTS: -Xms1024m -Xmx1024m
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      JAVA_TOOL_OPTIONS: "-Duser.home=$SNAP_USER_COMMON"
      PATH: $JAVA_HOME/jre/bin:$PATH
    plugs:
      - home
      - network
      - network-bind
