name: object-mappers
version: '1.0.0'
summary: |
  Object mappers playground
description: |
  Free and open source software application that considered different options for
  end-to-end object mappings

architectures:
  - build-on: armhf
  - build-on: arm64
  - build-on: amd64
  - build-on: i386

confinement: devmode
base: core18

parts:
  object-mappers:
    plugin: maven
    source: https://github.com/AlexRogalskiy/object-mappers-playground.git
    maven-openjdk-version: "11"
    source-type: git
    source-branch: master
    maven-options:
      - -DskipTests=true
      - -Dmaven.javadoc.skip=false
      - -B
      - -V
      - -P"test-jar","dev"
    override-build: |
      snapcraftctl build
      unzip -o DIST/object-mappers-*.zip -d $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - unzip

apps:
  object-mappers:
    extensions:
      - gnome-3-28
    command: java $JAVA_OPTS -jar ./modules/objectmappers-benchmarks/.build/bin/io.nullables.api.playground.objectmappers.benchmarks/benchmarks.jar
    environment:
      JAVA_OPTS: -Xms1024m -Xmx1024m
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/jre/bin:$PATH
    plugs:
      - home
      - network
      - network-bind
