name: object-mappers
version: '1.0.0'
version-script: |
  echo $(cat VERSION)-$(date +%Y%m%d)+$(git rev-parse --short HEAD)
summary: |
  Object mappers playground
description: |
  Free and open source software application that considered different options for
  end-to-end object mappings

architectures:
  - build-on: armhf
  - build-on: arm64
  - build-on: amd64
  - build-on: i386

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
base: core18

parts:
  object-mappers:
    plugin: maven
    source: https://github.com/AlexRogalskiy/object-mappers-playground.git
    maven-openjdk-version: "11"
    source-type: git
    source-branch: master
    source-depth: 1
    maven-options:
      - --batch-mode
      - --show-version
      - --errors
      - --lax-checksums
      - -DskipTests=true
      - -P test-jar, dev
#    override-build: |
#      snapcraftctl build
    build-packages:
      - openjdk-11-jdk
      - unzip
      - maven
    stage-packages:
      - openjdk-11-jre

apps:
  object-mappers:
    extensions:
      - gnome-3-28
    command: java $JAVA_OPTS -jar ./modules/objectmappers-benchmarks/.build/bin/io.nullables.api.playground.objectmappers.benchmarks/benchmarks.jar
    environment:
      JAVA_OPTS: -Xms1024m -Xmx1024m
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      JAVA_TOOL_OPTIONS: "-Duser.home=$SNAP_USER_COMMON"
      PATH: $JAVA_HOME/jre/bin:$PATH
    plugs:
      - home
      - network
      - network-bind
