name: allure-junit5-maven

on:
  push:
    branches-ignore:
      - '!master'

env:
  MAVEN_ARGS: >-
    --file pom.xml --no-transfer-progress --show-version --batch-mode --errors --lax-checksums

jobs:
  autotests:
    name: Run tests and generate Allure Report
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone for improving relevancy of SonarQube reporting
          fetch-depth: 0

      - uses: actions/cache@v1
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-${{ github.workflow }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.workflow }}-

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install dependencies
        run: |
          chmod +x ./mvnw
          ./mvnw dependency:go-offline compile compiler:testCompile $MAVEN_ARGS -DskipTests=true -P"test-jar","dev"

      - name: Run Test
        if: always()
        run: |
          chmod +x ./mvnw
          ./mvnw test $MAVEN_ARGS -P"test","test-jar","dev"
        continue-on-error: false

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: false
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        #id: allure-report
        with:
          allure_results: target/allure-results
          #gh_pages: gh-pages
          #allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
