name: pullrequest

on: pull_request

env:
  MAVEN_ARGS: >-
    --file pom.xml --no-transfer-progress --show-version --batch-mode --errors --lax-checksums

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone for improving relevancy of SonarQube reporting
          fetch-depth: 0

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with maven
        run: |
          chmod +x ./mvnw
          ./mvnw clean package $MAVEN_ARGS -P"test","test-jar","dev"

  automerge:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: ridedott/merge-me-action@v1.8.68
        if: github.actor == 'dependabot[bot]'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_LOGIN: dependabot[bot]
          PRESET: DEPENDABOT_MINOR
