# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
#machine:
#  environment:
#    JAVA_HOME: /usr/lib/jvm/java-9-oracle

dependencies:
  #  pre:
  #    - sudo add-apt-repository -y ppa:webupd8team/java; sudo apt-get update
  #    - echo "oracle-java9-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
  #    - echo "oracle-java9-installer shared/accepted-oracle-license-v1-1 seen true" | sudo debconf-set-selections
  #    - sudo apt-get -y install oracle-java9-installer
  #    - sudo apt-get install oracle-java9-set-default
  java:
    version: openjdk11

version: 2
jobs:
  build:
    parallelism: 2
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Run build in parallel
          command: mvn clean package --file pom.xml --show-version --batch-mode --errors --lax-checksums -DskipTests=true -P"test-jar","dev"
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Run tests in parallel
          command: mvn clean test --file pom.xml --show-version --batch-mode --errors --lax-checksums -P"test","test-jar","dev"

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
