# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

jobs:
  test:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    environment:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      JVM_OPTS: -Xmx3g
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Check environment
          command: env
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./mvnw
      - run:
          name: Run build
          command: ./mvnw clean test --file pom.xml --show-version --batch-mode --errors --lax-checksums -P"test","test-jar","dev"

  build:
    parallelism: 2
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    environment:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      JVM_OPTS: -Xmx3g
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }} # appends cache key with a hash of pom.xml file
            - v1-dependencies- # fallback in case previous cache key is not found
      - run:
          name: Check environment
          command: env
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./mvnw
      - run:
          name: Run build
          command: ./mvnw clean package --file pom.xml --show-version --batch-mode --errors --lax-checksums -DskipTests=true -P"test-jar","dev"
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
