# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

dependencies:
  pre:
    - sudo add-apt-repository ppa:linuxuprising/java
    - sudo apt-get update
    - sudo apt-get -y install oracle-java11-set-default

machine:
  environment:
    JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64

jobs:
  test:
    docker:
      - image: cimg/base:2020.11
    steps:
      - checkout
      - run: env
      - run: java -version
      - run: sudo chmod +x ./mvnw
      - run: ./mvnw clean test --file pom.xml --show-version --batch-mode --errors --lax-checksums -P"test","test-jar","dev"

  build:
    parallelism: 2
    docker:
      - image: cimg/base:2020.11
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }} # appends cache key with a hash of pom.xml file
            - v1-dependencies- # fallback in case previous cache key is not found
      - run: env
      - run: java -version
      - run: sudo chmod +x ./mvnw
      - run: ./mvnw clean package --file pom.xml --show-version --batch-mode --errors --lax-checksums -DskipTests=true -P"test-jar","dev"
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
