# https://github.com/git-chglog/git-chglog

style: github
template: CHANGELOG.tpl.md

info:
  title: CHANGELOG
  repository_url: https://github.com/AlexRogalskiy/object-mappers-playground

options:
  commits:
    sort_by: Scope
  commit_groups:
    group_by: Scope
    sort_by: Title
    title_maps:
      feat: Features
  header:
    pattern: '^(.*):\s*(.*)$'
    pattern_maps:
      - Scope
      - Subject
  issues:
    prefix:
      - "#"
  refs:
    actions:
      - Closes
      - Fixes
      - PullRequest
  notes:
    keywords:
      - BREAKING CHANGE
      - NOTE
  merges:
    pattern: "^Merge branch '(\\w+)'$"
    pattern_maps:
      - Source
  reverts:
    pattern: "^Revert \"([\\s\\S]*)\"$"
    pattern_maps:
      - Header
