name: Git

on: [ pull_request ]

jobs:
  lint:
    runs-on: ubuntu-18.04
    name: Lint Commit Messages

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Fetch origin
        run: git fetch origin
      - name: Event Sender
        run: echo ${{ github.event.sender.login }}
      - name: Lint commit message
        run: |
          echo "module.exports = {extends: ['@commitlint/config-conventional']}" > commitlint.config.js
          npx commitlint --from origin/${{ github.base_ref }} --to HEAD
