# This file is maintained in https://github.com/WeblateOrg/meta/
name: Issue labeled

on:
  issues:
    types: [ labeled ]

jobs:
  issueLabeled:
    runs-on: ubuntu-18.04
    steps:
      - name: Add backlog comment
        uses: peter-evans/create-or-update-comment@v1
        if: github.event.label.name == 'backlog'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            This issue has been added to the backlog. It is not scheduled on the Weblate roadmap, but it eventually might be implemented. In case you need this feature soon, please consider helping or push it by [funding the development](https://ko-fi.com/alexrogalskiy).

      - name: Add undecided comment
        uses: peter-evans/create-or-update-comment@v1
        if: github.event.label.name == 'undecided'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            This issue has been put aside. It is currently unclear if it will ever be implemented as it seems to cover too narrow of a use case or doesn't seem to fit into Weblate. Please try to clarify the use case or consider proposing something more generic to make it useful to more users.

      - name: Add question comment
        uses: peter-evans/create-or-update-comment@v1
        if: github.event.label.name == 'question'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            This issue looks more like a support question than an issue. We strive to answer these reasonably fast, but [purchasing the support subscription](https://weblate.org/support/) is not only more responsible and faster for your business but also makes Weblate stronger. In case your question is already answered, [making a donation](https://ko-fi.com/alexrogalskiy) is the right way to say thank you!

      - name: Add translate-toolkit comment
        uses: peter-evans/create-or-update-comment@v1
        if: github.event.label.name == 'translate-toolkit'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            The issue you've reported needs to be addressed in the [translate-toolkit](https://github.com/translate/translate/). Please file the issue there, and include links to any relevant specifications about the formats (if applicable).

      - name: Create comment
        if: ${{ github.event_name == 'pull_request_target'
          && github.event.action == 'closed'
          && github.event.pull_request.merged
          && !startsWith(github.event.pull_request.head.ref, 'dependabot/')
          && github.event.pull_request.base.ref == 'master' }}
        #       From a security perspective it's good practice to reference the commit hash
        #       https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#security
        uses: peter-evans/create-or-update-comment@41f3207a84f33bd70388036109082784d059dcaa
        with:
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            This pull request was merged to [${{ github.event.pull_request.base.ref }}](${{ github.event.repository.html_url }}/tree/${{ github.event.pull_request.base.ref }}) branch. This change is now waiting for deployment, which will usually happen within a few days. Stay tuned by joining our `#ops` channel on [Discord](https://discordapp.com/invite/HjJCwm5)!

            After deployment, changes are copied to [gh-pages](${{ github.event.repository.html_url }}/tree/gh-pages) branch: ![](https://img.shields.io/github/commit-status/${{ github.event.repository.full_name }}/gh-pages/${{ github.event.pull_request.merge_commit_sha }}.svg?label=deploy%20status)
