name: License

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  license-check:
    name: License Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Check License Headers
        run: |
          for d in ./modules/ ; do
              cd "$d"
              mvn -N license:check-file-header -Plicense
          done
