name: Java PR Builder

on:
  pull_request:
    branches: [ master ]
    types: [ opened, reopened, synchronize, labeled, unlabeled ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2.3.0
        with:
          java-version: 11

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache Maven Dependecies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ steps.get-date.outputs.date }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Some tests need screen access
      - name: Install xvfb
        run: sudo apt-get install -y xvfb

      # This worflow is only for building Pull Requests, the master branch runs Sonar analysis on the main repository.
      # SonarQube scan does not work for forked repositories.
      # See https://jira.sonarsource.com/browse/MMF-1371
      - name: Build with Maven
        run: xvfb-run mvn clean verify -DskipTests=true -Pdev,test-jar
