name: Validate

on: [ push, pull_request ]

jobs:
  validate:
    name: Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 2

      - name: Validate images
        uses: ./.github/workflows/validate
